// DO NOT EDIT THIS FILE!!! IT WILL BE AUTOMATICALLY GENERATED FROM src/i18n
/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "IP Adresse des Repetier-Server": {                                             "en": "IP Adress of Repetier-Server",                                               "de": "IP Adresse von Repetier-Server", },
    "Port(default 3344)": {                                                         "en": "Port(default 3344)",                                                         "de": "Port(Standard 3344), },
    "API-Key of Repetier-Server": {                                                 "en": "API-Key of Repetier-Server",                                                 "de": "API-Key von Repetier-Server", },
    "Intervall": {                                                                  "en": "Intervall (Sec.)",                                                           "de": "Abfrageintervall (Sek.)", },
};